In [1]:
def change_var(var):
    var = var*10
    
var = 10

In [2]:
import numpy as np

In [3]:
_roll = np.array([1, -1, -1, 1]) * 4

In [4]:
_roll

array([ 4, -4, -4,  4])

In [5]:
cmd = np.full(4, 8)
cmd

array([8, 8, 8, 8])

In [6]:
cmd+_roll

array([12,  4,  4, 12])

In [7]:
'Publishing command values: ' + ', '.join(map(str, _roll))

'Publishing command values: 4, -4, -4, 4'

In [8]:
1e-9 * 1000000000000

1000.0000000000001

In [11]:
a = np.float32(452.5225)
type(a)

numpy.float32

In [12]:
float(a)

452.5224914550781